### ISSUE TITLE
Add rm and or rmr cli option

### ISSUE THREAD

**Issue by feldoh** [feldoh/JZookeeperEdit#40]
The CLI should have the ability to delete nodes. This should be a really easy one. Just add a new parameter to the CliParameters class (be sure to add it to includesAction() too). Then do something very similar to the other functions in the ZkCli class except delete rather than read.

Note that there is a client.delete().deletingChildrenIfNeeded()... function.We definitely want this (i.e. rmr) but whether we also add a non-recursive delete is up to the implementer. If we did we'd want trying to delete a node with children to error (i.e. message to stderr and return code 1)

Remember we want to make this CLI friendly so I'd expect to be able to delete all the children of some parent node with something like this:

    java -jar JZookeeperEdit.jar -c localhost -p -l /some/path/with/kids | xargs java -jar JZookeeperEdit.jar -c localhost --rmr`

Another possibly nice option would be a --rm-children to give a nicer version of this.

**Comment by stangles** [comment]
Hi, I would like to work on this.

**Comment by feldoh** [comment]
Cool @stangles if you have any questions or need any help feel free to ask. There's also a [gitter](https://gitter.im/JZookeeperEdit/Lobby) if you prefer.
