### ISSUE TITLE
Add Windows to Travis Build

### ISSUE THREAD

**Issue by feldoh** [feldoh/JZookeeperEdit#80]
Travis should test that we can make a native package on Windows
https://docs.gluonhq.com/client/0.1.33/ contains the instructions

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll work on this.

**Comment by feldoh** [comment]
Great thanks for getting involved

**Comment by mohitsaxenaknoldus** [comment]
Hey @feldoh can you please provide more information?

**Comment by feldoh** [comment]
Sure. So there's kinda two halves for this. Happy to take it as two separate PRs for increased Hacktoberfest score ;)

If you look at the [travis.yml](https://github.com/feldoh/JZookeeperEdit/blob/develop/.travis.yml#L7) you'll see that at the moment it only builds on linux and osx. If you add Windows here it will start building on Windows too. However I don't think it'll work out of the box. Or at least it didn't previously.

So the task is basically just to get the thing to build on Windows. From line 27 onwards it should work regardless because the maven command is the same on any OS assuming it's on the PATH. But the meat of this problem is really just working out how to get a Windows machine set up to build a Java project and more annoyingly, a GRAALVM project because that's a lot less well supported and unfortunately Gluon switched to requiring it.

https://docs.travis-ci.com/user/reference/windows/ has good docs on all the tools the Travis Windows environment has. But for example it does not have Maven. Fortunately there is a maven [chocolatey package](https://community.chocolatey.org/packages/maven) so installing that should be easy enough.

The main aim here is that as an app (and a project) it needs to be able to build and run on all major operating systems. I know it does run on Windows, because I have run it from Windows without issue. But the setup was a bit annoying. Without a travis build checking that the project can still be built on Windows it's possible someone working on say a Mac might make a change that makes it not run on Windows (as someone did). So it would be good to make sure that the build is running on all three to verify it works on all three.

## Part 2
If you check the docs for Gluon [here](https://docs.gluonhq.com/#_gluonfxpackage) you'll see there is a `gluonfx:package` maven goal. This should allow us to make native packages for each OS so if you run it on OSX you get an app, on linux you get a deb (on Debian based systems like Ubuntu) or rpm (on Fedora based distros like Centos) and on Windows an msi or exe.

A year or so ago this worked easily (before Gluon). The extras specific for each package are in [the deploy folder](https://github.com/feldoh/JZookeeperEdit/tree/develop/src/main/deploy/package) The config for the old plugin was [here](https://github.com/feldoh/JZookeeperEdit/blob/6938e363da4eb49eb6bbab5e39c81eb10f71db7e/pom.xml#L147)

The problem is the old plugin made these friendly native packages but the early Gluon version did not. Pre Java9 I could just run `mvn jfx:native` and I'd get an MSI for Windows, an RPM a DEB etc that I was able to provide on BinTray for easy download for people that aren't Java devs. At the moment I only get a weird GRAAL binary that doesn't have the logo, can't be installed in the the start menu etc. It's something but it's not great.

Upgrading to the latest Gluon plugin and trying to get it to build at least one of these friendly package types again would be amazing. Again in terms of Hacktoberfest feel free to do it one package type at a time. So make the RPM work, make a PR make the MSI work, make a PR etc. You could farm out some easy points here and it's honestly the biggest annoyance for the people that use this in the real world right now. Most people still use the Java 8 version because they want a package. In theory there is nothing to do it should _just work_ but again I'd like to make sure we don't break it again so I want to make the Travis process build each type (where possible) so that means more Travis changes particularly on Windows because Gluon needs extra stuff for each one to work. Ideally I'd say hook this up to the package phase in Maven. I can offer more guidance on that if you get that far!
